repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks	
    rev: v4.5.0	
    hooks:	
    -   id: trailing-whitespace	
    -   id: end-of-file-fixer	
    -   id: double-quote-string-fixer	
-   repo: https://github.com/asottile/reorder_python_imports	
    rev: v3.12.0	
    hooks:	
    -   id: reorder-python-imports	
        args: [--py39-plus]
-   repo: https://github.com/asottile/pyupgrade	
    rev: v3.15.0	
    hooks:	
    -   id: pyupgrade
        args: [--py3-plus, --keep-percent-format]
-   repo: https://github.com/pre-commit/mirrors-autopep8	
    rev: v2.0.4	
    hooks:	
    -   id: autopep8	
        args: [--in-place, --indent-size=2, --aggressive, --ignore=E701, --max-line-length=120]
-   repo: https://github.com/PyCQA/flake8	
    rev: 6.1.0	
    hooks:	
    -   id: flake8	
        args: ["--ignore=E501,E111,E114,E701,E704"]

